FROM node:hydrogen-alpine3.19

RUN apk add --no-cache g++ make py3-pip

WORKDIR /app

COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json

RUN npm install

COPY . /app

RUN chmod +x ./entrypoint.dev.sh

CMD ["sh", "./entrypoint.dev.sh" ]
